name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: peterjgrainger/test-action@release-v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
