name: CI

on:
  push:
    branches:
      - master

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: peterjgrainger/action-create-branch@master
      with:
        branch: release-note-branch
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
